-- ARTICLES
CREATE TABLE ARTICLES (
    ID SERIAL,
    TITLE TEXT NOT NULL,
    ARTICLE_DATE TIMESTAMP NOT NULL,
    BODY TEXT NOT NULL,
    TAGS TEXT[] NOT NULL,
    CREATEDDATE TIMESTAMP NOT NULL DEFAULT current_timestamp
);
